name: Build executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6 pandas chardet
    - name: Build executable
      run: |
        pyinstaller --name="PhoneFilter" --onefile --windowed ProcessCsv.py
    - name: Upload Windows Build
      uses: actions/upload-artifact@v4
      with:
        name: PhoneFilter-Windows
        path: dist/PhoneFilter.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6 pandas chardet
    - name: Create Info.plist
      run: |
        echo '<?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleExecutable</key>
          <string>PhoneFilter</string>
          <key>CFBundleIconFile</key>
          <string>icon.icns</string>
          <key>CFBundleIdentifier</key>
          <string>com.phonefilter.app</string>
          <key>CFBundleName</key>
          <string>PhoneFilter</string>
          <key>CFBundlePackageType</key>
          <string>APPL</string>
          <key>CFBundleShortVersionString</key>
          <string>1.0.0</string>
          <key>LSMinimumSystemVersion</key>
          <string>10.15</string>
          <key>NSHighResolutionCapable</key>
          <true/>
        </dict>
        </plist>' > Info.plist
    - name: Build executable
      run: |
        pyinstaller --name="PhoneFilter" \
          --onefile \
          --windowed \
          --clean \
          --target-architecture universal2 \
          --osx-bundle-identifier="com.phonefilter.app" \
          ProcessCsv.py
    - name: Create app bundle
      run: |
        mkdir -p "dist/PhoneFilter.app/Contents/MacOS"
        mkdir -p "dist/PhoneFilter.app/Contents/Resources"
        cp Info.plist "dist/PhoneFilter.app/Contents/"
        mv "dist/PhoneFilter" "dist/PhoneFilter.app/Contents/MacOS/"
        chmod +x "dist/PhoneFilter.app/Contents/MacOS/PhoneFilter"
    - name: Upload macOS Build
      uses: actions/upload-artifact@v4
      with:
        name: PhoneFilter-MacOS
        path: dist/PhoneFilter.app