name: Build executables

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install pyinstaller PyQt6 pandas chardet
    - name: Build executable
      run: pyinstaller --name="PhoneFilter" --onefile --windowed ProcessCsv.py
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PhoneFilter-Windows
        path: dist/PhoneFilter.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install py2app PyQt6 pandas chardet
    - name: Create setup.py
      run: |
        echo 'from setuptools import setup
        APP = ["ProcessCsv.py"]
        DATA_FILES = []
        OPTIONS = {
            "argv_emulation": True,
            "packages": ["PyQt6", "pandas", "chardet"],
        }
        setup(
            app=APP,
            data_files=DATA_FILES,
            options={"py2app": OPTIONS},
            setup_requires=["py2app"],
        )' > setup.py
    - name: Build app
      run: python setup.py py2app
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: PhoneFilter-MacOS
        path: dist/PhoneFilter.app