name: Build executables

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install PyQt6 pandas chardet
    - name: Build executable
      run: |
        pyinstaller --name="PhoneFilter" --onefile --windowed ProcessCsv.py
    - name: Upload Windows Build
      uses: actions/upload-artifact@v3
      with:
        name: PhoneFilter-Windows
        path: dist/PhoneFilter.exe

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        pip install PyQt6 pandas chardet
    - name: Build app
      run: |
        python setup.py py2app
    - name: Upload macOS Build
      uses: actions/upload-artifact@v3
      with:
        name: PhoneFilter-MacOS
        path: dist/PhoneFilter.app